# Generated by Django 3.1.5 on 2021-01-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BussinessPart',
            fields=[
                ('description', models.CharField(help_text='描述', max_length=255, unique=True, verbose_name='描述')),
                ('name', models.CharField(max_length=64, verbose_name='商品名称')),
                ('uuid', models.UUIDField(default='08ec37925e5511ebb3d7784f434f97b9', editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('mbpn', models.TextField(db_index=True, max_length=128, unique=True)),
            ],
        ),
    ]
