# Generated by Django 3.1.5 on 2021-01-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussinesspart', '0003_auto_20210124_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinesspart',
            name='uuid',
            field=models.TextField(default='6de2dd425e5811eb8d36784f434f97b9', editable=False, primary_key=True, serialize=False),
        ),
    ]
