# Generated by Django 3.1.5 on 2021-01-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussinesspart', '0004_auto_20210124_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinesspart',
            name='uuid',
            field=models.TextField(default='9a86d4b65f2011eb8d94784f434f97b9', editable=False, primary_key=True, serialize=False),
        ),
    ]
