# Generated by Django 3.1.5 on 2021-01-25 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='分单号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分单列表',
                'verbose_name_plural': '分单列表',
            },
        ),
        migrations.CreateModel(
            name='ServiceCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='渠道名称')),
                ('code', models.CharField(max_length=20, verbose_name='渠道代码')),
            ],
            options={
                'verbose_name': '下单代码列表',
                'verbose_name_plural': '下单代码列表',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='订单号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='订单时间')),
                ('house_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipment.housebill', verbose_name='分单号')),
                ('inputer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.servicecode', verbose_name='渠道名称')),
            ],
            options={
                'verbose_name': '订单列表',
                'verbose_name_plural': '订单列表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_num', models.CharField(max_length=50, verbose_name='包裹号')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment', verbose_name='订单号')),
            ],
            options={
                'verbose_name': '包裹列表',
                'verbose_name_plural': '包裹列表',
                'unique_together': {('package_num', 'shipment')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='商品SKU')),
                ('name_cn', models.CharField(max_length=50, verbose_name='中文品名')),
                ('sku_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.package', verbose_name='包裹号')),
            ],
            options={
                'verbose_name': '商品列表',
                'verbose_name_plural': '商品列表',
                'unique_together': {('package', 'sku')},
            },
        ),
    ]
