# Generated by Django 3.1.5 on 2021-01-24 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bussinesspart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('description', models.CharField(help_text='描述', max_length=255, unique=True, verbose_name='描述')),
                ('bussiness_type', models.CharField(choices=[('TAC', '精品'), ('TYRE', '轮胎')], default='TAC', help_text='业务类型', max_length=5, verbose_name='业务类型')),
                ('status', models.CharField(choices=[(0, 'Confirmed'), (1, 'Pending'), (2, 'Done'), (3, 'Pending Arrived'), (4, 'Rejected'), (5, 'Cancelling'), (6, 'Cancelled'), (-2, 'Failed'), (-1, 'New')], default=0, help_text='订单状态', max_length=2, verbose_name='订单状态')),
                ('uuid', models.UUIDField(default='08ec96f65e5511ebb3d7784f434f97b9', editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('logistics_created_at', models.DateTimeField(verbose_name='物流时间')),
                ('arrival_at', models.DateTimeField(verbose_name='订单到货时间')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='经销商')),
            ],
            options={
                'verbose_name': '订单表',
                'db_table': 'dealer_orders',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itmes', to='order.order')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bussinesspart.bussinesspart')),
            ],
        ),
    ]
