# Generated by Django 3.1.5 on 2021-01-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210124_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Confirmed'), (1, 'Pending'), (2, 'Done'), (3, 'Pending Arrived'), (4, 'Rejected'), (5, 'Cancelling'), (6, 'Cancelled'), (-2, 'Failed'), (-1, 'New')], default=0, help_text='订单状态', max_length=2, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default='6de345485e5811eb8d36784f434f97b9', editable=False, primary_key=True, serialize=False),
        ),
    ]
